/* DON'T EDIT THIS FILE. IT IS GENERATED BY scripts/data-gen */

import type { TechStackData } from '~/types/response';

const techStackData: TechStackData = [
  {
    id: 1,
    attributes: {
      name: 'React.js',
      url: 'https://reactjs.org/',
      logo: {
        data: {
          id: 3,
          attributes: {
            alternativeText: 'React',
            height: 512,
            mime: 'image/png',
            name: 'reactjs.png',
            provider_metadata: {
              public_id: 'rofisyahrul.com/assets/reactjs_aae2bdc86e',
              resource_type: 'image',
            },
            width: 512,
          },
        },
      },
    },
  },
  {
    id: 2,
    attributes: {
      name: 'Next.js',
      url: 'https://nextjs.org/',
      logo: {
        data: {
          id: 4,
          attributes: {
            alternativeText: 'Next.js icon',
            height: 180,
            mime: 'image/png',
            name: 'Nextjs',
            provider_metadata: {
              public_id:
                'rofisyahrul.com/assets/apple_touch_icon_49e6586208',
              resource_type: 'image',
            },
            width: 180,
          },
        },
      },
    },
  },
  {
    id: 3,
    attributes: {
      name: 'Tailwind CSS',
      url: 'https://tailwindcss.com/',
      logo: {
        data: {
          id: 5,
          attributes: {
            alternativeText: 'Tailwind CSS Icon',
            height: 33,
            mime: 'image/png',
            name: 'tailwindcss-mark.png',
            provider_metadata: {
              public_id:
                'rofisyahrul.com/assets/tailwindcss_mark_7ad7faf0ce',
              resource_type: 'image',
            },
            width: 54,
          },
        },
      },
    },
  },
  {
    id: 4,
    attributes: {
      name: 'TypeScript',
      url: 'https://www.typescriptlang.org/',
      logo: {
        data: {
          id: 6,
          attributes: {
            alternativeText: 'TypeScript',
            height: 192,
            mime: 'image/png',
            name: 'typescript.png',
            provider_metadata: {
              public_id:
                'rofisyahrul.com/assets/typescript_d33326fd16',
              resource_type: 'image',
            },
            width: 192,
          },
        },
      },
    },
  },
  {
    id: 5,
    attributes: {
      name: 'Supabase',
      url: 'https://supabase.com/',
      logo: {
        data: {
          id: 11,
          attributes: {
            alternativeText: 'Supabase Icon',
            height: 180,
            mime: 'image/png',
            name: 'supabase.png',
            provider_metadata: {
              public_id: 'rofisyahrul.com/assets/supabase_f42706269b',
              resource_type: 'image',
            },
            width: 180,
          },
        },
      },
    },
  },
  {
    id: 6,
    attributes: {
      name: 'Svelte',
      url: 'https://svelte.dev/',
      logo: {
        data: {
          id: 29,
          attributes: {
            alternativeText: 'svelte',
            height: 128,
            mime: 'image/png',
            name: 'svelte.png',
            provider_metadata: {
              public_id: 'rofisyahrul.com/assets/svelte_f4ebac16e9',
              resource_type: 'image',
            },
            width: 128,
          },
        },
      },
    },
  },
  {
    id: 7,
    attributes: {
      name: 'Liveblocks',
      url: 'https://liveblocks.io/',
      logo: {
        data: {
          id: 30,
          attributes: {
            alternativeText: 'liveblocks',
            height: 400,
            mime: 'image/png',
            name: 'liveblocks.png',
            provider_metadata: {
              public_id:
                'rofisyahrul.com/assets/liveblocks_290ffee78b',
              resource_type: 'image',
            },
            width: 400,
          },
        },
      },
    },
  },
];

export default techStackData;
