import path from 'path';

export const API_URL = 'http://localhost:1337';
export const dataDirPath = path.resolve(__dirname, '../../app/data');
export const PAGE = 1;
export const PAGE_SIZE = 100;
export const TOP_LINE = `/* DON'T EDIT THIS FILE. IT IS GENERATED BY scripts/data-gen */`;
